### ISSUE TITLE
Calculating co-optimals of two isomorphic graphs yields empty output graph

### ISSUE THREAD

**Issue by fncnt** [mk36fyvy/multivitamin#13]
Running 
```
multiVitamin -c Structure2D_CID_6440490.json.graph Structure2D_CID_9963391.json.graph -a vf2
```
on [current master](https://github.com/mk36fyvy/multivitamin/commit/30c4d4ea1f3ceba7aab689db92c96fb967baeaef) produces empty output graph `.graph` and no co-optimals. See [samplegraphs.zip](https://github.com/mk36fyvy/multivitamin/files/4159641/samplegraphs.zip) for sample data.

**Comment by mk36fyvy** [comment]
You are using VF2, which only checks for graph-graph- or graph-subgraph-isomorphism. Even though, the graphs are very similar, either one does not "completely" fit into the other. This is why the program fails. You could rerun the thing with subVF2, but it will likely take a long time, because the graphs are already quite big.

**Comment by mk36fyvy** [comment]
Given that the two provided graphs are totally equal (my bad), I will try to investigate and fix, why the alignment did not work
